---
  - hosts: "{{ host }}"
    gather_facts: False
    remote_user: root
	  tasks:
      - name: 把 文件01 和 文件02 和 sh脚本 传输到服务器
        copy:
          src: '{{ item.src }}'
          dest: '{{ item.dest }}'
          mode: 0755
        with_items:
          - { src: '文件01',dest: '文件01' }
          - { src: '文件02',dest: '文件02' }
	        - { src: 'sh脚本',dest: 'sh脚本' }
      - name: 运行服务
        shell: "{{ cmd }}"